let DB=null, month=new Date(), token=localStorage.token||'', adminToken=localStorage.adminToken||'', LANG=localStorage.lang||'IT', slideTimer=null, slideIndex=0;
const T={IT:{home:'Home',login:'Login',register:'Registrati',dashboard:'Area cliente',bookNow:'Prenota',availabilityBooking:'Disponibilità e richiesta',calendar:'Calendario',newBooking:'Nuova richiesta'},EN:{home:'Home',login:'Login',register:'Register',dashboard:'Guest area',bookNow:'Book',availabilityBooking:'Availability and request',calendar:'Calendar',newBooking:'New request'},FR:{home:'Accueil',login:'Connexion',register:'Inscription',dashboard:'Espace client',bookNow:'Réserver',availabilityBooking:'Disponibilité et demande',calendar:'Calendrier',newBooking:'Nouvelle demande'}};
function txt(obj){return (obj&&typeof obj==='object')?(obj[LANG.toLowerCase()]||obj.it||obj.en||''):(obj||'')}
function serviceById(id){return (DB.services||[]).find(s=>s.id===id)}
function qs(x){return document.querySelector(x)} function qsa(x){return [...document.querySelectorAll(x)]} function j(o){return JSON.stringify(o)}
function showPage(id){qsa('.page').forEach(p=>p.classList.remove('active'));qs('#'+id).classList.add('active'); window.scrollTo({top:0,behavior:'smooth'}); if(id==='dashboard') loadDashboard(); if(id==='admin'&&adminToken) loadAdmin();}
function setLang(l){LANG=l;localStorage.lang=l;qsa('[data-t]').forEach(e=>{if(T[l]?.[e.dataset.t])e.textContent=T[l][e.dataset.t]}); renderPublic();}
async function api(url,opt={}){opt.headers=opt.headers||{};if(!(opt.body instanceof FormData))opt.headers['Content-Type']='application/json'; if(token)opt.headers.Authorization='Bearer '+token; let r=await fetch(url,opt); let data=await r.json().catch(()=>({})); if(!r.ok) throw new Error(data.error||'Errore'); return data;}
async function adminApi(url,opt={}){opt.headers=opt.headers||{};if(!(opt.body instanceof FormData))opt.headers['Content-Type']='application/json'; if(adminToken)opt.headers.Authorization='Bearer '+adminToken; let r=await fetch(url,opt); let data=await r.json().catch(()=>({})); if(!r.ok) throw new Error(data.error||'Errore admin'); return data;}
async function loadPublic(){DB=await api('/api/public'); if(DB.settings.logo){logo.src=DB.settings.logo;logo.classList.remove('hidden')} setLang(LANG); renderPublic(); renderCalendar();}
function renderPublic(){if(!DB)return; siteDesc.textContent=txt(DB.settings.descriptions); if(DB.settings.logo){logo.src=DB.settings.logo;logo.classList.remove('hidden')}
  houses.innerHTML=DB.houses.map(h=>`<div class="card" onclick="openHouse('${h.id}')">${h.photos?.[0]?`<img src="${h.photos[0]}">`:`<img src="${DB.settings.logo||'/data/uploads/woodenbridge-logo.jpeg'}">`}<div><h2>${h.name}</h2><p>${h.description||''}</p><p>👥 Fino a ${h.capacity} persone ${h.bedrooms?` · 🛏️ ${h.bedrooms} camere`:''}</p><button>Scopri di più</button></div></div>`).join('');
  let svcs=(DB.services||[]).slice(0,4); features.innerHTML=svcs.map(s=>`<div class="feature"><span class="ico">${s.icon||'✓'}</span><div><b>${txt(s.name)}</b><br><small>${txt(s.description)}</small></div></div>`).join('');
  let photos=DB.houses.flatMap(h=>h.photos||[]); if(!photos.length) photos=[DB.settings.logo||'/data/uploads/woodenbridge-logo.jpeg']; clearInterval(slideTimer); slideIndex=Math.min(slideIndex,photos.length-1); window.__slides=photos; drawSlide(); slideTimer=setInterval(nextSlide,4500);
}
function drawSlide(){let photos=window.__slides||[]; let src=photos[slideIndex]||DB?.settings?.logo||''; slider.innerHTML=src?`<img class="slide" src="${src}">`:`<div class="slide"></div>`; dots.innerHTML=photos.map((_,i)=>`<span class="${i===slideIndex?'active':''}" onclick="slideIndex=${i};drawSlide()"></span>`).join('')}
function nextSlide(){let photos=window.__slides||[]; if(!photos.length)return; slideIndex=(slideIndex+1)%photos.length; drawSlide()}
function prevSlide(){let photos=window.__slides||[]; if(!photos.length)return; slideIndex=(slideIndex-1+photos.length)%photos.length; drawSlide()}
function openHouse(id){let h=DB.houses.find(x=>x.id===id); if(!h)return; let services=(h.services||[]).map(serviceById).filter(Boolean); houseDetailContent.innerHTML=`<h1>${h.name}</h1><p>${h.description||''}</p><p><b>Capienza:</b> fino a ${h.capacity} persone ${h.bedrooms?` · <b>Camere:</b> ${h.bedrooms}`:''}</p><div class="gallery">${(h.photos&&h.photos.length?h.photos:[DB.settings.logo]).map(p=>`<img src="${p}">`).join('')}</div><h2>Servizi disponibili</h2><div class="serviceGrid">${services.map(s=>`<div class="servicePill"><h3>${s.icon||'✓'} ${txt(s.name)}</h3><p>${txt(s.description)}</p></div>`).join('')||'<p>Nessun servizio configurato.</p>'}</div><br><button class="primary" onclick="showPage('home');document.getElementById('bookingBox').scrollIntoView({behavior:'smooth'})">Prenota questa casa</button>`; showPage('houseDetail')}

function statusForDate(d){let pending=DB.bookings.some(b=>b.status==='pending'&&dateIn(d,b.startDate,b.endDate)); let busy=DB.bookings.some(b=>b.status==='confirmed'&&dateIn(d,b.startDate,b.endDate)); let blocked=Object.values(DB.availability||{}).some(x=>x[d]==='blocked'); if(busy||blocked)return'busy'; if(pending)return'pending'; return'free';}
function dateIn(d,s,e){return new Date(d)>=new Date(s)&&new Date(d)<new Date(e)}
function renderCalendar(){let y=month.getFullYear(),m=month.getMonth(); monthTitle.textContent=month.toLocaleString(LANG.toLowerCase(),{month:'long',year:'numeric'}); let first=new Date(y,m,1), start=(first.getDay()+6)%7, days=new Date(y,m+1,0).getDate(); let html=['L','M','M','G','V','S','D'].map(x=>`<div class="dow">${x}</div>`).join(''); for(let i=0;i<start;i++)html+='<div></div>'; for(let d=1;d<=days;d++){let iso=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`, st=statusForDate(iso); html+=`<div class="day ${st}" onclick="clickDate('${iso}','${st}')"><b>${d}</b><small>${st==='free'?'Libero':st==='pending'?'Sospesa':'Non disponibile'}</small></div>`} calendar.innerHTML=html;}
function moveMonth(n){month.setMonth(month.getMonth()+n);renderCalendar()}
function clickDate(iso,st){ if(st==='free'){if(confirm('Vuoi fare una nuova prenotazione da questa data?')){showPage('home');qs('[name=startDate]').value=iso;qs('[name=endDate]').value=isoPlus(iso,1);}} else if(st==='pending') alert('Questa data è temporaneamente sospesa perché c’è una richiesta in attesa.'); else alert('Questa data non è disponibile.');}
function isoPlus(iso,n){let d=new Date(iso);d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
function agencyToggle(v){agencyName.classList.toggle('hidden',v!=='agency')}
regForm.onsubmit=async e=>{e.preventDefault();let b=Object.fromEntries(new FormData(regForm));try{let r=await api('/api/register',{method:'POST',body:j(b)});regMsg.textContent=r.message+(r.devCode?' Codice test: '+r.devCode:'');verifyEmail.value=b.email;verifyBox.classList.remove('hidden');regForm.reset();}catch(err){regMsg.textContent=err.message}}
async function verifyEmail(){try{await api('/api/verify',{method:'POST',body:j({email:verifyEmail.value,code:verifyCode.value})});alert('Email verificata. Ora puoi fare login.');showPage('login')}catch(e){alert(e.message)}}
loginForm.onsubmit=async e=>{e.preventDefault();try{let r=await api('/api/login',{method:'POST',body:j(Object.fromEntries(new FormData(loginForm)))});token=r.token;localStorage.token=token;localStorage.user=JSON.stringify(r.user);loginMsg.textContent='Login effettuato';showPage('dashboard')}catch(err){loginMsg.textContent=err.message}}
async function forgotPassword(){let email=prompt('Inserisci la tua email'); if(!email)return; let r=await api('/api/password-reset',{method:'POST',body:j({email})}); alert('Se la mail esiste, riceverai il link di reset.'+(r.devToken?' Token test: '+r.devToken:''));}
quoteForm.oninput=()=>{let minors=+quoteForm.minors.value,babies=+quoteForm.babies.value;gates.classList.toggle('hidden',!(minors||babies))}
quoteForm.onsubmit=async e=>{e.preventDefault();let b=Object.fromEntries(new FormData(quoteForm));try{let r=await api('/api/quote',{method:'POST',body:j(b)});quoteResult.innerHTML=r.options.length?r.options.map(o=>`<div class="bookingCard"><b>${o.label}</b><br>${o.nights} notti - Totale €${o.total}<br><button type="button" onclick="bookOption('${o.id}')">Richiedi questa opzione</button></div>`).join(''):'<p>Nessuna disponibilità per queste date.</p>';}catch(err){quoteResult.textContent=err.message}}
async function bookOption(optionId){if(!token){alert('Devi registrarti o fare login prima di prenotare.');showPage('login');return}let fd=Object.fromEntries(new FormData(quoteForm));let u=JSON.parse(localStorage.user||'{}');fd.optionId=optionId;fd.guestName=prompt('Nome ospite / intestatario booking',`${u.firstName||''} ${u.lastName||''}`.trim())||'';fd.guestPhone=prompt('Telefono ospite',u.phone||'')||'';fd.guestEmail=prompt('Email ospite',u.email||'')||'';try{let r=await api('/api/bookings',{method:'POST',body:j(fd)});showConfirmation(r.booking);await loadPublic();}catch(e){alert(e.message)}}
function showConfirmation(b){let alloc=(b.allocations||[]).map(a=>`${a.houseId}: ${a.guests} ospiti`).join(', ');let html=`<div class="panel" id="printConf"><h1>${DB.settings.siteName}</h1>${DB.settings.logo?`<img src="${DB.settings.logo}" style="max-width:120px">`:''}<h2>Booking confirmation</h2><p><b>Nome:</b> ${b.guestName}</p><p><b>Arrivo:</b> ${b.startDate} - <b>Partenza:</b> ${b.endDate}</p><p><b>Ospiti:</b> ${b.adults} adulti, ${b.minors} minorenni, ${b.babies} neonati</p><p><b>Alloggio:</b> ${alloc}</p><p><b>Totale:</b> €${b.total}</p><p>Per informazioni: ${DB.settings.contactName} - ${DB.settings.contactPhone}</p><p>Check-out possibilmente entro le ${DB.settings.checkout}. Wi-Fi: <b>${DB.settings.wifiPassword}</b></p><p>${DB.settings.welcomeMessages?.it||''}</p><button onclick="print()">Stampa</button><button onclick="showPage('dashboard')">Vai alla tua area</button></div>`;document.querySelector('main').insertAdjacentHTML('afterbegin',html);document.getElementById('printConf').scrollIntoView({behavior:'smooth'});}
async function loadDashboard(){if(!token){userBar.innerHTML='Fai login per vedere i booking.';return}let u=JSON.parse(localStorage.user||'{}');userBar.innerHTML=`<p><b>${u.type==='agency'?u.agencyName:u.firstName+' '+u.lastName}</b> <button onclick="logout()">Logout</button></p>`;try{let r=await api('/api/my/bookings');dashBookings.innerHTML=r.bookings.map(b=>bookingHtml(b,true)).join('')||'<p>Nessun booking.</p>';}catch(e){dashBookings.textContent=e.message}}
function logout(){localStorage.removeItem('token');localStorage.removeItem('user');token='';showPage('login')}
function bookingHtml(b,customer=false){let wa=`Booking confirmation%0ANome ospite: ${encodeURIComponent(b.guestName)}%0AOspiti: ${b.adults+b.minors+b.babies}%0ACheck-in: ${b.startDate}%0ACheck-out: ${b.endDate}%0AInfo: Stephan 3482782639`;return `<div class="bookingCard ${b.status}"><b>${b.guestName}</b> <em>${b.status}</em><br>${b.startDate} → ${b.endDate} | €${b.total}<br>Adulti ${b.adults}, minorenni ${b.minors}, neonati ${b.babies}<br>${customer?`<div class="actions"><button onclick="requestCancel('${b.id}')">Richiedi cancellazione</button><a target="_blank" href="https://wa.me/?text=${wa}"><button>WhatsApp confirmation</button></a></div>`:''}</div>`}
async function requestCancel(id){let reason=prompt('Motivo cancellazione');if(!reason)return;try{await api('/api/my/bookings/'+id+'/cancel-request',{method:'POST',body:j({reason})});loadDashboard()}catch(e){alert(e.message)}}
async function adminLogin(){try{let r=await api('/api/admin/login',{method:'POST',body:j({username:adminUser.value,password:adminPass.value})});adminToken=r.token;localStorage.adminToken=adminToken;loadAdmin()}catch(e){alert(e.message)}}
async function loadAdmin(){qs('#adminLogin').classList.add('hidden');qs('#adminArea').classList.remove('hidden');await adminTab('list')}
async function adminTab(tab){let db=await adminApi('/api/admin/db');
 if(tab==='list')adminContent.innerHTML=`<h3>Tutti i booking</h3>${db.bookings.map(b=>`<div class="bookingCard ${b.status}"><b>${b.guestName}</b> ${b.status}<br>${b.startDate} → ${b.endDate} | €${b.total}<br>Fonte: ${b.source} ${b.cancelRequest?'<p class="notice">Richiesta cancellazione: '+b.cancelRequest.reason+'</p>':''}<div class="actions"><button onclick="admAccept('${b.id}')">Accetta</button><button onclick="admEdit('${b.id}')">Modifica</button><button onclick="admCancel('${b.id}')">Annulla</button><button onclick="admDelete('${b.id}')">Cancella</button></div></div>`).join('')||'<p>Nessun booking.</p>'}`;
 if(tab==='new'){adminContent.innerHTML=`<h3>Nuovo booking admin</h3><form id="adminNew" class="form"><input name="guestName" placeholder="Nome ospite"><input name="guestPhone" placeholder="Telefono"><input name="guestEmail" placeholder="Email"><div class="row"><input type="date" name="startDate"><input type="date" name="endDate"><input type="number" name="adults" value="2"></div><div class="row"><input type="number" name="minors" value="0"><input type="number" name="babies" value="0"><select name="optionId"><option value="wb">Woodenbridge</option><option value="ai">Aigoviano</option><option value="combo">Combinato</option></select></div><textarea name="notes" placeholder="Note"></textarea><button class="primary">Crea confermato</button></form>`; adminNew.onsubmit=async e=>{e.preventDefault();try{await adminApi('/api/admin/bookings',{method:'POST',body:j(Object.fromEntries(new FormData(adminNew)))});adminTab('list')}catch(x){alert(x.message)}};}
 if(tab==='avail'){adminContent.innerHTML=`<h3>Blocca / libera date multiple</h3><form id="avForm" class="form"><select name="houseId">${db.houses.map(h=>`<option value="${h.id}">${h.name}</option>`).join('')}</select><div class="row"><input type="date" name="startDate"><input type="date" name="endDate"><select name="status"><option value="blocked">Occupata/bloccata</option><option value="free">Libera</option></select></div><button class="primary">Salva disponibilità</button></form>`; avForm.onsubmit=async e=>{e.preventDefault();await adminApi('/api/admin/availability',{method:'POST',body:j(Object.fromEntries(new FormData(avForm)))});alert('Salvato');await loadPublic();renderCalendar()};}
 if(tab==='prices'){adminContent.innerHTML=`<h3>Tariffe speciali per giorno</h3><p>Lascia prezzo vuoto per tornare al prezzo automatico.</p><form id="prForm" class="form"><select name="houseId">${db.houses.map(h=>`<option value="${h.id}">${h.name}</option>`).join('')}</select><div class="row"><input type="date" name="startDate"><input type="date" name="endDate"><input type="number" name="price" placeholder="€/persona/notte"></div><button class="primary">Salva prezzo</button></form>`; prForm.onsubmit=async e=>{e.preventDefault();await adminApi('/api/admin/prices',{method:'POST',body:j(Object.fromEntries(new FormData(prForm)))});alert('Tariffe salvate')};}
 if(tab==='content'){adminContent.innerHTML=`<h3>Testi e logo</h3><form id="setForm" class="form"><label>Nome contatto<input name="contactName" value="${db.settings.contactName||''}"></label><label>Telefono<input name="contactPhone" value="${db.settings.contactPhone||''}"></label><label>Email<input name="contactEmail" value="${db.settings.contactEmail||''}"></label><label>Password Wi‑Fi<input name="wifiPassword" value="${db.settings.wifiPassword||''}"></label><label>Descrizione IT<textarea name="descIt">${db.settings.descriptions?.it||''}</textarea></label><label>Descrizione EN<textarea name="descEn">${db.settings.descriptions?.en||''}</textarea></label><label>Descrizione FR<textarea name="descFr">${db.settings.descriptions?.fr||''}</textarea></label><button class="primary">Salva testi base</button></form><hr><h4>Logo</h4><input type="file" id="logoFile"><button onclick="uploadLogo()">Carica logo</button>`; setForm.onsubmit=async e=>{e.preventDefault();let f=Object.fromEntries(new FormData(setForm));await adminApi('/api/admin/settings',{method:'POST',body:j({contactName:f.contactName,contactPhone:f.contactPhone,contactEmail:f.contactEmail,wifiPassword:f.wifiPassword,descriptions:{it:f.descIt,en:f.descEn,fr:f.descFr}})});alert('Salvato');await loadPublic()};}
 if(tab==='houses'){adminContent.innerHTML=`<h3>Gestionale case</h3><div class="notice">Da qui puoi aggiungere case, cambiare capienza, descrizione, foto e servizi collegati alla casa.</div><form id="newHouse" class="form"><h4>Aggiungi nuova casa</h4><div class="row"><input name="name" placeholder="Nome casa"><input name="capacity" type="number" placeholder="Posti letto" value="2"><input name="bedrooms" type="number" placeholder="Camere" value="1"></div><textarea name="description" placeholder="Descrizione"></textarea><button class="primary">Aggiungi casa</button></form><hr>${db.houses.map(h=>houseAdminCard(h,db.services)).join('')}`; newHouse.onsubmit=async e=>{e.preventDefault();await adminApi('/api/admin/houses',{method:'POST',body:j(Object.fromEntries(new FormData(newHouse)))});alert('Casa aggiunta');adminTab('houses');await loadPublic()};}
 if(tab==='services'){adminContent.innerHTML=`<h3>Gestionale servizi</h3><form id="svcForm" class="form"><div class="row"><input name="icon" placeholder="Icona es. 📶"><input name="nameIt" placeholder="Nome IT"><input name="nameEn" placeholder="Nome EN"><input name="nameFr" placeholder="Nome FR"></div><textarea name="descIt" placeholder="Descrizione IT"></textarea><textarea name="descEn" placeholder="Descrizione EN"></textarea><textarea name="descFr" placeholder="Descrizione FR"></textarea><button class="primary">Aggiungi / aggiorna servizio</button></form><hr><div class="serviceGrid">${db.services.map(s=>`<div class="servicePill"><h3>${s.icon||'✓'} ${txt(s.name)}</h3><p>ID: ${s.id}</p><p>${txt(s.description)}</p><button onclick="deleteService('${s.id}')">Cancella</button></div>`).join('')}</div>`; svcForm.onsubmit=async e=>{e.preventDefault();await adminApi('/api/admin/services',{method:'POST',body:j(Object.fromEntries(new FormData(svcForm)))});alert('Servizio salvato');adminTab('services');await loadPublic()};}
}
function houseAdminCard(h,services){return `<div class="bookingCard"><h3>${h.name}</h3><form id="house_${h.id}" class="form"><input name="name" value="${h.name||''}"><div class="row"><input name="capacity" type="number" value="${h.capacity||2}"><input name="bedrooms" type="number" value="${h.bedrooms||1}"></div><textarea name="description">${h.description||''}</textarea><label>Servizi</label><div class="serviceGrid">${services.map(s=>`<label class="servicePill"><input type="checkbox" name="services" value="${s.id}" ${(h.services||[]).includes(s.id)?'checked':''}> ${s.icon||'✓'} ${txt(s.name)}</label>`).join('')}</div><button type="button" onclick="saveHouseFull('${h.id}')">Salva casa</button></form><h4>Foto</h4><div class="gallery">${(h.photos||[]).map(p=>`<img src="${p}">`).join('')}</div><input type="file" id="files_${h.id}" multiple><div class="progress"><div id="bar_${h.id}" class="bar"></div></div><button onclick="uploadPhotos('${h.id}')">Carica foto multiple</button>${!['woodenbridge','aigoviano'].includes(h.id)?`<button onclick="deleteHouse('${h.id}')">Cancella casa</button>`:''}</div>`}
async function saveHouseFull(id){let form=qs('#house_'+id);let fd=new FormData(form);let body={name:fd.get('name'),capacity:Number(fd.get('capacity')),bedrooms:Number(fd.get('bedrooms')),description:fd.get('description'),services:fd.getAll('services')};await adminApi('/api/admin/houses/'+id,{method:'POST',body:j(body)});alert('Casa salvata');adminTab('houses');await loadPublic()}
async function deleteHouse(id){if(confirm('Cancellare questa casa?')){await adminApi('/api/admin/houses/'+id,{method:'DELETE'});adminTab('houses');await loadPublic()}}
async function deleteService(id){if(confirm('Cancellare servizio?')){await adminApi('/api/admin/services/'+id,{method:'DELETE'});adminTab('services');await loadPublic()}}
async function admAccept(id){await adminApi('/api/admin/bookings/'+id+'/accept',{method:'POST',body:'{}'});adminTab('list');loadPublic()}
async function admCancel(id){let reason=prompt('Motivo annullamento')||'';await adminApi('/api/admin/bookings/'+id+'/cancel',{method:'POST',body:j({reason})});adminTab('list');loadPublic()}
async function admDelete(id){if(confirm('Cancellare definitivamente?')){await adminApi('/api/admin/bookings/'+id,{method:'DELETE'});adminTab('list');loadPublic()}}
async function admEdit(id){let startDate=prompt('Nuova data arrivo YYYY-MM-DD, lascia vuoto per non cambiare');let endDate=prompt('Nuova data partenza YYYY-MM-DD, lascia vuoto per non cambiare');let body={}; if(startDate)body.startDate=startDate;if(endDate)body.endDate=endDate;await adminApi('/api/admin/bookings/'+id,{method:'PATCH',body:j(body)});adminTab('list');loadPublic()}
async function saveHouse(id){await adminApi('/api/admin/houses/'+id,{method:'POST',body:j({description:qs('#desc_'+id).value})});alert('Descrizione salvata');loadPublic()}
function uploadWithProgress(url,fd,bar){return new Promise((res,rej)=>{let x=new XMLHttpRequest();x.open('POST',url);x.setRequestHeader('Authorization','Bearer '+adminToken);x.upload.onprogress=e=>{if(e.lengthComputable)bar.style.width=(e.loaded/e.total*100)+'%'};x.onload=()=>x.status<300?res(JSON.parse(x.responseText)):rej(new Error(x.responseText));x.onerror=()=>rej(new Error('Upload fallito'));x.send(fd)})}
async function uploadPhotos(id){let inp=qs('#files_'+id), fd=new FormData();[...inp.files].forEach(f=>fd.append('photos',f));if(!inp.files.length)return alert('Seleziona una o più foto');await uploadWithProgress('/api/admin/upload/'+id,fd,qs('#bar_'+id));alert('Foto caricate in data/uploads');await loadPublic();adminTab('houses')}
async function uploadLogo(){if(!logoFile.files[0])return alert('Seleziona il logo');let fd=new FormData();fd.append('logo',logoFile.files[0]);await uploadWithProgress('/api/admin/logo',fd,{style:{}});alert('Logo caricato');await loadPublic();}
loadPublic();
