const express=require('express'),session=require('express-session'),bcrypt=require('bcryptjs'),multer=require('multer'),fs=require('fs'),path=require('path'),cors=require('cors'),nodemailer=require('nodemailer');
const app=express(),PORT=process.env.PORT||3000,DATA_DIR=process.env.DATA_DIR||path.join(__dirname,'data'),DB_FILE=path.join(DATA_DIR,'db.json'),UPLOAD_DIR=path.join(__dirname,'public','uploads');
const ADMIN_USER=process.env.ADMIN_USER||'admin',ADMIN_PASS_HASH=process.env.ADMIN_PASS_HASH||bcrypt.hashSync(process.env.ADMIN_PASSWORD||'woodenbridge2026',10);
fs.mkdirSync(DATA_DIR,{recursive:true});fs.mkdirSync(UPLOAD_DIR,{recursive:true});
const baseDb={properties:{woodenbridge:{name:'Woodenbridge House',beds:7,description:'Casa accogliente per famiglie e gruppi, fino a 7 posti letto.',photos:[]},aigoviano:{name:'Casa Dell’Aigoviano',beds:2,description:'Soluzione intima con letto matrimoniale, fino a 2 posti letto.',photos:[]}},availability:{woodenbridge:{},aigoviano:{}},bookings:[],users:[],emailCodes:{},pricing:{defaultAdultChild:30,woodenbridgeSingle:50,woodenbridgeTwo:35,aigoviano:30,dailyOverrides:{}},settings:{siteTitle:'Woodenbridge House',subtitle:'Disponibilità e richieste prenotazione',terms:'Email e numero di telefono devono essere validi: senza contatti corretti la prenotazione non potrà andare a buon fine.'}};
if(!fs.existsSync(DB_FILE))fs.writeFileSync(DB_FILE,JSON.stringify(baseDb,null,2));
function readDb(){const db=JSON.parse(fs.readFileSync(DB_FILE,'utf8'));return {...baseDb,...db,properties:{...baseDb.properties,...db.properties},availability:{...baseDb.availability,...db.availability},pricing:{...baseDb.pricing,...db.pricing},settings:{...baseDb.settings,...db.settings}}}
function writeDb(db){fs.writeFileSync(DB_FILE,JSON.stringify(db,null,2))} function authed(req,res,next){if(req.session?.admin)return next();res.status(401).json({error:'Non autorizzato'})} function logged(req,res,next){if(req.session?.userId)return next();res.status(401).json({error:'Devi accedere come cliente'})} function cleanDate(d){return/^\d{4}-\d{2}-\d{2}$/.test(d)}
function nights(from,to){let a=new Date(from+'T00:00'),b=new Date(to+'T00:00'),out=[];while(a<b){out.push(a.toISOString().slice(0,10));a.setDate(a.getDate()+1)}return out}
function busy(db,pid,from,to){return nights(from,to).some(d=>db.availability[pid]?.[d]==='busy'||db.availability[pid]?.[d]==='pending')}
function dailyPrice(db,pid,date,count){let ov=db.pricing.dailyOverrides?.[date]?.[pid]; if(ov!=null)return Number(ov)*count; if(pid==='aigoviano')return db.pricing.aigoviano*count; if(count===1)return db.pricing.woodenbridgeSingle; if(count===2)return db.pricing.woodenbridgeTwo*2; return db.pricing.defaultAdultChild*count}
function quote(db,from,to,adults,children,babies){const paying=Number(adults||0)+Number(children||0), dates=nights(from,to), opts=[]; if(!paying||!dates.length)return[]; const sum=(pid,c)=>dates.reduce((t,d)=>t+dailyPrice(db,pid,d,c),0); const add=(label,parts)=>{if(parts.every(p=>!busy(db,p.id,from,to)))opts.push({label,parts,total:parts.reduce((t,p)=>t+sum(p.id,p.guests),0),nights:dates.length})}; if(paying<=2){add('Woodenbridge House',[{id:'woodenbridge',name:db.properties.woodenbridge.name,guests:paying}]);add('Casa Dell’Aigoviano',[{id:'aigoviano',name:db.properties.aigoviano.name,guests:paying}])} else if(paying<=5){add('Woodenbridge House',[{id:'woodenbridge',name:db.properties.woodenbridge.name,guests:paying}])} else if(paying<=7){add('Tutti a Woodenbridge House',[{id:'woodenbridge',name:db.properties.woodenbridge.name,guests:paying}]); add(`${paying-1} a Woodenbridge + 1 a Casa Dell’Aigoviano`,[{id:'woodenbridge',name:db.properties.woodenbridge.name,guests:paying-1},{id:'aigoviano',name:db.properties.aigoviano.name,guests:1}])} else if(paying<=9){add('7 a Woodenbridge + resto a Casa Dell’Aigoviano',[{id:'woodenbridge',name:db.properties.woodenbridge.name,guests:7},{id:'aigoviano',name:db.properties.aigoviano.name,guests:paying-7}])} return opts.map((o,i)=>({...o,id:String(i),babies}))}
async function sendCode(email,code){if(process.env.SMTP_HOST){let tr=nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:process.env.SMTP_SECURE==='true',auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}});await tr.sendMail({from:process.env.MAIL_FROM||process.env.SMTP_USER,to:email,subject:'Codice verifica Woodenbridge House',text:`Il tuo codice di verifica è: ${code}`});return true} return false}
const storage=multer.diskStorage({destination:UPLOAD_DIR,filename:(req,file,cb)=>cb(null,Date.now()+'-'+file.originalname.replace(/[^a-z0-9._-]/gi,'_'))}); const upload=multer({storage,limits:{fileSize:8*1024*1024,files:20},fileFilter:(req,file,cb)=>cb(null,/^image\//.test(file.mimetype))});
app.use(cors());app.use(express.json({limit:'2mb'}));app.use(session({secret:process.env.SESSION_SECRET||'change-this-secret',resave:false,saveUninitialized:false,cookie:{maxAge:1000*60*60*24*30}}));app.use(express.static(path.join(__dirname,'public')));
app.get('/api/public',(req,res)=>{let db=readDb();res.json({properties:db.properties,availability:db.availability,pricing:db.pricing,settings:db.settings,user:req.session.userId?db.users.find(u=>u.id===req.session.userId):null})});
app.post('/api/send-code',async(req,res)=>{let{email}=req.body;if(!/.+@.+\..+/.test(email||''))return res.status(400).json({error:'Email non valida'});let db=readDb(),code=String(Math.floor(100000+Math.random()*900000));db.emailCodes[email.toLowerCase()]={code,expires:Date.now()+15*60*1000};writeDb(db);let sent=await sendCode(email,code);res.json({ok:true,message:sent?'Codice inviato via email':'Codice generato. In locale/senza SMTP il codice è: '+code,devCode:sent?undefined:code})});
app.post('/api/register',async(req,res)=>{let{username,password,firstName,lastName,address,phone,email,code}=req.body,db=readDb(),em=(email||'').toLowerCase();let rec=db.emailCodes[em];if(!rec||rec.code!==String(code)||rec.expires<Date.now())return res.status(400).json({error:'Codice email errato o scaduto'}); if(!username||!password||!firstName||!lastName||!address||!phone||!em)return res.status(400).json({error:'Compila tutti i campi'}); if(db.users.some(u=>u.username===username||u.email===em))return res.status(400).json({error:'Utente o email già registrati'});let u={id:Date.now().toString(),username,passHash:await bcrypt.hash(password,10),firstName,lastName,address,phone,email:em,createdAt:new Date().toISOString()};db.users.push(u);delete db.emailCodes[em];writeDb(db);req.session.userId=u.id;res.json({ok:true,user:{...u,passHash:undefined}})});
app.post('/api/client-login',async(req,res)=>{let db=readDb(),u=db.users.find(x=>x.username===req.body.username||x.email===req.body.username);if(u&&await bcrypt.compare(req.body.password,u.passHash)){req.session.userId=u.id;return res.json({ok:true})}res.status(401).json({error:'Credenziali cliente errate'})});app.post('/api/client-logout',(req,res)=>{delete req.session.userId;res.json({ok:true})});
app.post('/api/quote',(req,res)=>{let db=readDb(),{from,to,adults,children,babies}=req.body;if(!cleanDate(from)||!cleanDate(to))return res.status(400).json({error:'Date non valide'});res.json({options:quote(db,from,to,adults,children,babies)})});
app.post('/api/bookings',logged,(req,res)=>{let db=readDb(),u=db.users.find(x=>x.id===req.session.userId),{from,to,adults,children,babies,needsGates,optionId}=req.body,opts=quote(db,from,to,adults,children,babies),opt=opts.find(o=>o.id===String(optionId));if(!opt)return res.status(400).json({error:'Opzione non disponibile'});let b={id:Date.now().toString(),createdAt:new Date().toISOString(),status:'pending',userId:u.id,customer:{firstName:u.firstName,lastName:u.lastName,email:u.email,phone:u.phone,address:u.address},from,to,adults:Number(adults),children:Number(children||0),babies:Number(babies||0),needsGates:!!needsGates,option:opt,total:opt.total};db.bookings.unshift(b);opt.parts.forEach(p=>nights(from,to).forEach(d=>db.availability[p.id][d]='pending'));writeDb(db);res.json({ok:true,message:'Richiesta prenotazione inviata. Le date sono in arancione finché non vengono confermate.',booking:b})});
app.post('/api/login',async(req,res)=>{if(req.body.username===ADMIN_USER&&await bcrypt.compare(req.body.password,ADMIN_PASS_HASH)){req.session.admin=true;return res.json({ok:true})}res.status(401).json({error:'Credenziali errate'})});app.post('/api/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true})));app.get('/api/admin',authed,(req,res)=>res.json(readDb()));
app.put('/api/property/:id',authed,(req,res)=>{let db=readDb(),id=req.params.id;if(!db.properties[id])return res.status(404).json({error:'Struttura non trovata'});db.properties[id]={...db.properties[id],name:req.body.name||db.properties[id].name,beds:Number(req.body.beds)||db.properties[id].beds,description:req.body.description??db.properties[id].description};writeDb(db);res.json({ok:true})});
app.post('/api/property/:id/photos',authed,upload.array('photos',20),(req,res)=>{let db=readDb(),id=req.params.id;if(!db.properties[id])return res.status(404).json({error:'Struttura non trovata'});let urls=req.files.map(f=>'/uploads/'+f.filename);db.properties[id].photos.push(...urls);writeDb(db);res.json({ok:true,urls})});app.delete('/api/property/:id/photo',authed,(req,res)=>{let db=readDb(),id=req.params.id;db.properties[id].photos=db.properties[id].photos.filter(p=>p!==req.body.url);writeDb(db);res.json({ok:true})});
app.put('/api/availability/:id',authed,(req,res)=>{let db=readDb(),id=req.params.id,{dates,status}=req.body;if(!db.properties[id]||!Array.isArray(dates)||!['free','busy'].includes(status))return res.status(400).json({error:'Dati non validi'});dates.forEach(d=>{if(cleanDate(d)){if(status==='free')delete db.availability[id][d];else db.availability[id][d]='busy'}});writeDb(db);res.json({ok:true})});
app.put('/api/pricing',authed,(req,res)=>{let db=readDb();db.pricing={...db.pricing,...req.body};writeDb(db);res.json({ok:true})});app.put('/api/settings',authed,(req,res)=>{let db=readDb();db.settings={...db.settings,...req.body};writeDb(db);res.json({ok:true})});
app.put('/api/bookings/:id',authed,(req,res)=>{let db=readDb(),b=db.bookings.find(x=>x.id===req.params.id);if(!b)return res.status(404).json({error:'Prenotazione non trovata'});b.status=req.body.status;if(req.body.status==='accepted')b.option.parts.forEach(p=>nights(b.from,b.to).forEach(d=>db.availability[p.id][d]='busy'));if(req.body.status==='rejected')b.option.parts.forEach(p=>nights(b.from,b.to).forEach(d=>{if(db.availability[p.id][d]==='pending')delete db.availability[p.id][d]}));writeDb(db);res.json({ok:true})});
app.listen(PORT,()=>console.log('Woodenbridge booking on http://localhost:'+PORT));
